# Generated by Django 5.0.6 on 2024-06-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('NA', '_'), ('PC', 'Решается'), ('WA', 'Неправильно'), ('OK', 'Правильно')], default='NA', max_length=15, verbose_name='Состояние задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usertaskenroll', to='singer.task', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usertaskenroll', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'db_table': 'usertaskenroll',
            },
        ),
    ]
