# Generated by Django 5.0.6 on 2024-07-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0004_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
