# Generated by Django 5.0.6 on 2024-07-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0005_delete_views'),
        ('singer', '0005_task_cnt_bm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugs',
            unique_together={('user', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='favouritetask',
            unique_together={('user', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='usertaskenroll',
            unique_together={('user', 'task')},
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('NA', '_'), ('PC', 'Решается'), ('WA', 'Неправильно'), ('OK', 'Правильно')], default='NA', max_length=15, verbose_name='Состояние задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useranswers', to='singer.task', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useranswers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Попытка пользователя',
                'verbose_name_plural': 'Попытки пользователей',
                'db_table': 'useranswers',
            },
        ),
    ]
