# Generated by Django 5.0.6 on 2024-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cnt_likes',
            field=models.IntegerField(default=2, verbose_name='Кол-во лайков'),
            preserve_default=False,
        ),
    ]
