# Generated by Django 5.0.6 on 2024-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_task_cnt_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cnt_views',
            field=models.IntegerField(null=True, verbose_name='Просмотры'),
        ),
    ]
