# Generated by Django 5.0.6 on 2024-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0004_alter_task_cnt_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cnt_bm',
            field=models.IntegerField(default=0, verbose_name='Кол-во zakladki'),
            preserve_default=False,
        ),
    ]
