# Generated by Django 5.0.6 on 2024-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0005_task_cnt_bm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cnt_bm',
            field=models.IntegerField(null=True, verbose_name='Кол-во zakladki'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cnt_likes',
            field=models.IntegerField(null=True, verbose_name='Кол-во лайков'),
        ),
    ]
