# Generated by Django 5.0.6 on 2024-07-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0006_alter_task_cnt_bm_alter_task_cnt_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(max_length=30, verbose_name='Название'),
        ),
    ]
