# Generated by Django 5.0.6 on 2024-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0007_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cnt_bm',
            field=models.IntegerField(default=0, verbose_name='Кол-во zakladki'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cnt_likes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cnt_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
